[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "madnet-stereo"
version = "1.0.0"
description = "MADNet: Real-time self-adaptive deep stereo estimation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=4.11.0",
    "matplotlib>=3.10.6",
    "pillow>=11.3.0",
    "keras>=3.11.3",
    "jupyter>=1.1.1",
    "wandb>=0.28.1",
    "tensorflow[and-cuda]>=2.21.0",
    "tensorboard>=2.21.0",
]
